import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms",
  description: `The terms that govern use of ${site.name}.`,
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="August 20, 2026">
      <p>
        These terms govern your use of {site.name}. By creating an account you agree
        to them.
      </p>

      <h2>Your account</h2>
      <p>
        You are responsible for keeping your password and API keys secret, and for
        everything done with them. Tell us immediately if a key is exposed and we
        will help you rotate it.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Only install the tracker on sites you own or are authorised to instrument.</li>
        <li>
          Do not use the service to collect personal data through custom properties,
          or to circumvent the privacy design described in our privacy policy.
        </li>
        <li>Do not attempt to read data belonging to another workspace.</li>
        <li>Do not resell raw access to the API outside the terms of a Platform plan.</li>
        <li>
          Only connect a social account you are authorised to post from, and only
          schedule content you have the right to publish.
        </li>
        <li>
          Do not use Orbit, our AI assistant, to generate content that is illegal,
          infringing, or that impersonates someone without their consent.
        </li>
      </ul>

      <h2>Connected social accounts</h2>
      <p>
        Scheduling posts to LinkedIn or another network we support requires you to
        authorise that connection yourself. We publish only what you compose and
        schedule — never anything we generate or select on your behalf — and only
        while the connection remains valid. If the network revokes access, changes
        its API, or a post fails for any reason, we will surface that failure
        rather than retry silently or substitute different content. You are
        responsible for complying with that network&apos;s own terms of use.
      </p>

      <h2>Orbit, our AI assistant</h2>
      <p>
        Orbit's answers are generated by third-party AI models and may be
        incorrect, incomplete, or out of date. Treat its output as a starting
        point, not as advice you act on unverified — this applies especially to
        anything Orbit drafts for you to publish.
      </p>

      <h2>Plans and billing</h2>
      <p>
        Paid plans are billed monthly in advance through Razorpay and can be
        cancelled at any time; cancellation takes effect at the end of the current
        period. If you exceed your pageview allowance we will contact you before
        restricting anything.
      </p>

      <h2>Availability</h2>
      <p>
        We aim for high availability and publish an SLA on Platform plans. On free
        plans the service is provided as-is, without a uptime guarantee. Features
        that depend on a third party — social publishing, Orbit, SEO audits — are
        also subject to that third party&apos;s own availability.
      </p>

      <h2>Your data</h2>
      <p>
        The analytics data collected for your sites, the form responses you
        collect, and the content you schedule to social accounts all belong to
        you. You can export or delete any of it at any time. If you close your
        account we delete it, including any connected social account tokens.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms. Material changes will be announced by email before
        they take effect.
      </p>

      <h2>Contact</h2>
      <p>
        Reach us at <a href={`mailto:${site.email}`}>{site.email}</a>.
      </p>
    </LegalPage>
  );
}
