import type { Doc } from "@/lib/docs";
import { H2, P, Ul, Li, Callout } from "@/components/prose";

function Body() {
  return (
    <>
      <P>
        Branding controls how a workspace looks to the people filling out its
        forms — the business name, logo, and accent color shown on public
        forms and payment windows — plus two attribution marks Quantalog adds
        by default.
      </P>

      <H2 id="your-brand">Your brand</H2>
      <Ul>
        <Li><b>Business name</b> — shown in the form header and respondent emails.</Li>
        <Li><b>Logo</b> — upload a file or pick one from the Media Library.</Li>
        <Li><b>Brand color</b> — the accent used for buttons and highlights on public forms and payment windows.</Li>
      </Ul>
      <P>
        A live preview next to the settings shows a mocked form and payment
        window updating as you change these fields, so you can check the look
        before saving.
      </P>

      <H2 id="credits">Credits</H2>
      <Ul>
        <Li><b>Powered-by footer</b> — a small attribution shown on public forms, thank-you screens, and respondent emails.</Li>
        <Li><b>AI image watermark</b> — marks images generated by Orbit AI as AI-made.</Li>
      </Ul>

      <Callout>
        Full customization, including turning off the powered-by footer, is a
        Pro feature. Free workspaces see a read-only preview of these settings.
      </Callout>

      <H2 id="saving">Saving changes</H2>
      <P>
        A save bar appears only while you have unsaved changes. Press{" "}
        <b>Escape</b> or use <b>Discard</b> to drop them and revert to the
        last saved branding.
      </P>
    </>
  );
}

export const branding: Doc = {
  slug: "branding",
  title: "Branding",
  description:
    "Customize the name, logo, and accent color shown on your public forms and payment windows.",
  category: "Workspace",
  order: 2,
  Body,
};
